// Supermemory Client for Local Instance
import fs from 'node:fs';
import path from 'node:path';

export type Result<T> = { success: true; data: T } | { success: false; error: string };

export interface DocumentSummary {
	id: string;
	createdAt: string;
	metadata?: Record<string, unknown> | null;
}

export interface Document extends DocumentSummary {
	content: string | null;
}

export interface SearchResult {
	documentId: string;
	createdAt?: string;
	chunks?: { content: string }[];
}

export class SupermemoryClient {
	baseUrl: string;
	apiKey: string;

	constructor(options: { baseUrl?: string; apiKey?: string } = {}) {
		this.baseUrl = options.baseUrl || process.env.SUPERMEMORY_API_URL || 'http://127.0.0.1:6767';
		let key = options.apiKey || process.env.SUPERMEMORY_API_KEY || '';

		// If key is dummy or unset, use the real key generated by the server in data/
		if (!key || key === 'sm_local_key') {
			try {
				key = fs.readFileSync(path.resolve(import.meta.dir, '../data/api-key'), 'utf-8').trim();
			} catch {
				key = '';
			}
		}

		this.apiKey = key;
	}

	getHeaders(): Record<string, string> {
		const headers: Record<string, string> = {
			'Content-Type': 'application/json',
		};
		if (this.apiKey) headers.Authorization = `Bearer ${this.apiKey}`;
		return headers;
	}

	async isHealthy(): Promise<boolean> {
		try {
			const res = await fetch(`${this.baseUrl}/v3/search/spaces`, {
				headers: this.getHeaders(),
				signal: AbortSignal.timeout(3000),
			});
			return res.status === 200;
		} catch {
			return false;
		}
	}

	/**
	 * JSON request that never throws: { success, data } or { success: false, error }
	 */
	async request<T>(method: string, urlPath: string, body?: unknown): Promise<Result<T>> {
		try {
			const res = await fetch(`${this.baseUrl}${urlPath}`, {
				method,
				headers: this.getHeaders(),
				body: body ? JSON.stringify(body) : undefined,
				signal: AbortSignal.timeout(5000),
			});
			if (!res.ok) {
				return { success: false, error: `HTTP ${res.status}: ${await res.text()}` };
			}
			return { success: true, data: (await res.json()) as T };
		} catch (err) {
			return { success: false, error: (err as Error).message };
		}
	}

	/**
	 * Add a document / memory entry into Supermemory
	 */
	addDocument({
		content,
		containerTags = [],
		metadata = {},
	}: {
		content: string;
		containerTags?: string[];
		metadata?: Record<string, unknown>;
	}) {
		return this.request<{ id: string; status: string }>('POST', '/v3/documents', {
			content,
			containerTags,
			metadata: { ...metadata, timestamp: new Date().toISOString() },
		});
	}

	/**
	 * Newest-first document list (metadata only, no content). Includes documents still
	 * being processed, so a memory written by another agent seconds ago is already visible.
	 */
	async listDocuments({
		containerTags = [],
		limit = 50,
	}: {
		containerTags?: string[];
		limit?: number;
	}): Promise<DocumentSummary[]> {
		const res = await this.request<{ memories?: DocumentSummary[] }>('POST', '/v3/documents/list', {
			containerTags,
			limit,
			sort: 'createdAt',
			order: 'desc',
		});
		return res.success ? res.data.memories || [] : [];
	}

	async getDocument(id: string): Promise<Document | null> {
		const res = await this.request<Document>('GET', `/v3/documents/${encodeURIComponent(id)}`);
		return res.success ? res.data : null;
	}

	/**
	 * Search project memories using /v3/search (vector search over chunks)
	 */
	async searchMemories({
		q,
		containerTags = [],
		limit = 10,
		chunkThreshold = 0.05,
	}: {
		q: string;
		containerTags?: string[];
		limit?: number;
		chunkThreshold?: number;
	}): Promise<{ results: SearchResult[]; error?: string }> {
		const res = await this.request<{ results?: SearchResult[] }>('POST', '/v3/search', {
			q,
			limit,
			chunkThreshold,
			containerTags,
		});
		return res.success ? { results: res.data.results || [] } : { results: [], error: res.error };
	}
}
